export const LOGGER_MODULE_OPTIONS = "LOGGER_MODULE_OPTIONS";
export const LOGGER_PROVIDER = "LOGGER_PROVIDER";

export const TMS_MODULE_OPTIONS = "TMS_MODULE_OPTIONS";
export const TMS_SERVICE_PROVIDER = "TMS_PROVIDER";

export const INFLUX_DB_MODULE_OPTIONS = "INFLUX_DB_MODULE_OPTIONS";
export const INFLUX_DB_SERVICE_PROVIDER = "INFLUX_DB_SERVICE_PROVIDER";

export const TEST_RUNS_AGREGATOR_SERVICE_PROVIDER = "TEST_RUNS_AGREGATOR_SERVICE_PROVIDER";
export const TEST_RUNS_AGREGATOR_MODULE_OPTIONS = "TEST_RUNS_AGREGATOR_MODULE_OPTIONS";

export const BUCKET_EXECUTOR_MODULE_OPTIONS = "BUCKET_EXECUTOR_MODULE_OPTIONS";
export const BUCKET_EXECUTOR_SERVICE_PROVICER = "BUCKET_EXECUTOR_SERVICE_PROVICER";
