tms:
    base_url: "https://api.qase.io/v1/"
    bucket_size: 100

agregator:
    track_duration_of_empty_cases: false
    recursive_counting_of_steps: true
    initial_offset: 0

influxdb:
    save_points_bucket_size: 500
    schema:
        test_run:
            measurment_name: "test run"
            steps_number: "steps number"
            duration: "duration"
            is_automation: "is automation run"
            id: "run id"
        test_case:
            measurment_name: "test case"
            steps_number: "steps number"
            duration: "duration"
            is_automation: "is automation run"
            id: "case id"
            run_id: "run id"
            automation_status: "automation status"
        backlog_case:
          measurment_name: "backlog case"
          steps_number: "steps number"
          case_name: "case name"
          id: "case id"
          automation_status: "automation status"

logger:
  level: "info"
